version: "3.8"

networks:
  inventory_network:
    driver: bridge
services:
  broker:
    image: apache/kafka:latest
    container_name: broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://broker:9092,CONTROLLER://broker:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - inventory_network

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:29092
    depends_on:
      - broker
    volumes:
      - /tmp/config.yml:/config.yml
    networks:
      - inventory_network

  backend:
    container_name: backend
    build: ./backend
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=FBnvkjzqjWqJfXJs
      - MONGO_URI=mongodb://mongodb:27017/inventory_db
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres-db:5432/inventory_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=postgres-db
      - DATABASE_NAME=inventory_db
      - DATABASE_PORT=5432
      - BROKER_ADDRESS=broker:9092
    depends_on:
      - postgres-db
      - mongodb
      - broker
    networks:
      - inventory_network

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    networks:
      - inventory_network

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
    restart: unless-stopped
    networks:
      - inventory_network

  postgres-db:
    image: postgres:13.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - inventory_network
